# Generated by Django 2.1.7 on 2019-02-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startuprank.Startup')),
            ],
        ),
    ]
