# Generated by Django 2.1.7 on 2019-02-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0002_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='startup',
        ),
        migrations.AddField(
            model_name='startup',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
