# Generated by Django 2.1.7 on 2019-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0003_auto_20190217_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
