# Generated by Django 2.1.7 on 2019-02-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0004_auto_20190219_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='vote_score',
        ),
    ]
