# Generated by Django 2.1.7 on 2019-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0008_auto_20190223_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
