# Generated by Django 2.1.7 on 2019-02-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0010_auto_20190224_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='votes',
        ),
    ]
