# Generated by Django 2.1.7 on 2019-02-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0011_remove_startup_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startuprank.Startup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
