# Generated by Django 2.1.7 on 2019-02-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0014_auto_20190224_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
