# Generated by Django 2.1.7 on 2019-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuprank', '0015_startup_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(blank=True, upload_to='startup_image'),
        ),
    ]
